version: 0.2

env:
  variables:
    IMAGE_NAME: "devops-agent-demo"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
      - echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - export FULL_IMAGE="$DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG"

  build:
    commands:
      - echo "Building Docker image $FULL_IMAGE"
      - docker build -t "$FULL_IMAGE" .

  post_build:
    commands:
      - echo "Pushing $FULL_IMAGE"
      - docker push "$FULL_IMAGE"
      - echo "Push completed"
